# Introdução ao NumPy

In [1]:
import numpy as np

Substitui as liastas do Python:
- As listas são muito flexíveis -> Tem alto consumo de memória e alto custo de processamento

Array do NumPy:
- Tem tamanho fixo
- Mesmo tipo da linguagem C

Fornece vários tipos de bibliotecas para processamento de dados

In [3]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1,2,3,], [4, 5, 6]])
d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [5]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(5,)
(2, 3)
(2, 2, 3)


In [6]:
x = [1,3,4]
a = np.asarray(x)
print(x)

[1, 3, 4]


In [10]:
astrings = np.array(["banana", "maca"], dtype = "S")
print(astrings)

[b'banana' b'maca']


In [14]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a[1,4]

10

Ordenação

In [15]:
a = np.array([17,20,3,6,5])
np.sort(a)

array([ 3,  5,  6, 17, 20])

Concatenação

In [16]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])
print(np.concatenate((x, y), axis = 0)) # concatenar pelas colunas


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])
print(np.concatenate((x, y), axis = 1)) # concatenar pelas linhas

[[1 2 5 6]
 [3 4 7 8]]


Busca

In [21]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print(a[a < 7])

[1 2 3 4 5 6]


In [22]:
maiores_sete = (a > 7)
print(a[maiores_sete])

[ 8  9 10 11 12]


In [23]:
c = a[(a > 2) & (a < 11)] # & e, | ou
print(c)

[ 3  4  5  6  7  8  9 10]


In [24]:
np.where((a > 2) & (a < 11)) # retorna os indices

(array([0, 0, 1, 1, 1, 1, 2, 2], dtype=int64),
 array([2, 3, 0, 1, 2, 3, 0, 1], dtype=int64))

In [27]:
b = np.array([0, 1, 2, 3, 4, 5])
idx = np.where(b > 3)
print(idx)
print(b[idx])

(array([4, 5], dtype=int64),)
[4 5]


Operações

In [29]:
a1 = np.array([1,2])
a2 = np.ones(2, dtype=int)

print(a1 + a2)
print(a1 * a2)
print(a1 - a2)

print(a1 * 10)

print(a1.sum())

[2 3]
[1 2]
[0 1]
[10 20]
3


Randômicos

In [31]:
from numpy import random

x =random.randint(100, size = (5, 4))
print(x)

[[62 76 15 36]
 [28 29  6 49]
 [53 38 98 85]
 [78 53  1 89]
 [34 64 29 12]]


In [32]:
x = random.rand(10)
print(x)

[0.17237909 0.39627497 0.6834318  0.14991751 0.24590332 0.13254606
 0.21172283 0.11262459 0.39415007 0.26286843]


In [33]:
x = random.choice([3,5,7,9], p=[0.1,0.3,0.5,0.1], size = (20))
print(x)

[5 5 9 7 5 7 5 7 9 5 7 7 9 7 7 7 5 7 7 5]


Entrada e Saída

In [36]:
a = np.array([1,2,3,4,5])
np.savetxt("out.txt", a) # salva em uma arquivo com cda conteúdo em uma linha
b = np.loadtxt("out.txt")
c = np.array(b, dtype = int)
print(c)

[1 2 3 4 5]
